### ISSUE TITLE
save png of the whole page + html

### ISSUE THREAD

**Issue by fede-green** [integratedexperts/behat-screenshot#18]
Hello, 

is there a way to save a screenshot of the whole page in stead of the "fold" only and to save also the html?

I tried using

`IntegratedExperts\BehatScreenshotExtension:
      dir: %paths.base%/screenshots
      fail: true
      purge: false
      png: true
      html: true`

with no luck :)

thanks for the great extension!

**Comment by alexdesignworks** [comment]
@fede-green 
>>is there a way to save a screenshot of the whole page in stead of the "fold" only
No, the screenshot is taken by the driver of what the "browser" window shows, which is what a user would see.
There may be a later implementation to achieve this.

>> and to save also the html?
Saving to both HTML and image at the same time is not supported. By default, for Selenium/Phantomjs drivers, the screenshot is an image, while for CURL-based drivers it is an HTML.

**Comment by fede-green** [comment]
sorry  @alexdesignworks i started again working on behat stuff, but i still can't find a way of saving the whole page screenshot. Could you help me out? :)
