### ISSUE TITLE
new behat function will be saved in screenshotContext.php

### ISSUE THREAD

**Issue by litodagodog** [integratedexperts/behat-screenshot#19]
When i add new function in my .feature it will be saved in below not in featurecontext.php
u C:\behat\vendor\integratedexperts\behat-screenshot\src\IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext.php - `I click the element "Client Login"` definition added

**Comment by alexdesignworks** [comment]
@litodagodog
Sorry, but I do not understand what you description means. Could you please re-word it.

**Comment by alexdesignworks** [comment]
closing because of  no response
