### ISSUE TITLE
Add config flag to remove all screenshots before new test run

### ISSUE THREAD

**Issue by alexdesignworks** [integratedexperts/behat-screenshot#5]
- config param `purge: 1`
- env var `BEHAT_SCREENSHOT_PURGE=1`, overrides config param, so that one-time command could be ran:
```
BEHAT_SCREENSHOT_PURGE=1 vendor/bin/behat
```
- update readme file.

**Comment by bladeaweb** [comment]
[Closed by PR #6](https://github.com/integratedexperts/behat-screenshot/pull/6)
